var Json=[
    {
        "id": 1,
        "grupo": "T1",
        "estudiantes": [
            {
                "id": 1,
                "cedula": "10001",
                "nombre": "jerxon",
                "apellido": "correa",
                "direccion": "calle 1 #2",
                "acudiente": "maria lizaraso",
                "telefono": "3112812609",
                "estado": "",
                "salon": "",
                "trainer": "",
                "riesgo": "",
                "ruta": "",
                "fechaIni": "12-03-2024",
                "fechaFin": "13-04-2024",
                "ocupado": "",
                "grupo": ""
            },
            {
                "id": 2,
                "cedula": "10002",
                "nombre": "Enrique",
                "apellido": "Mejia",
                "direccion": "call 1 #3",
                "acudiente": "eduardo guerrero",
                "telefono": "3188653147",
                "estado": "",
                "salon": "",
                "trainer": "",
                "riesgo": "",
                "ruta": "",
                "fechaIni": "12-03-2024",
                "fechaFin": "13-04-2024",
                "ocupado": "",
                "grupo": "T1"
            },
            {
                "id": 3,
                "cedula": "10003",
                "nombre": "Carolina",
                "apellido": "Ruiz",
                "direccion": "Calle 1 #4",
                "acudiente": "Jose Vidal",
                "telefono": "3866060",
                "estado": "",
                "salon": "",
                "trainer": "",
                "riesgo": "",
                "ruta": "",
                "fechaIni": "12-03-2024",
                "fechaFin": "13-04-2024",
                "ocupado": "",
                "grupo": "T1"
            },
            {
                "id": 4,
                "cedula": "10004",
                "nombre": "Tomas",
                "apellido": "Canto",
                "direccion": "Calle 1 #5",
                "acudiente": "Maria Bendeck",
                "telefono": "3741504",
                "estado": "",
                "salon": "",
                "trainer": "",
                "riesgo": "",
                "ruta": "",
                "fechaIni": "12-03-2024",
                "fechaFin": "13-04-2024",
                "ocupado": "",
                "grupo": "T1"
            },
            {
                "id": 5,
                "cedula": "10005",
                "nombre": "Celina",
                "apellido": "Acosta",
                "direccion": "Calle 1 #6",
                "acudiente": "Ricardo Benitez",
                "telefono": "3226947547",
                "estado": "",
                "salon": "",
                "trainer": "",
                "riesgo": "",
                "ruta": "",
                "fechaIni": "12-03-2024",
                "fechaFin": "13-04-2024",
                "ocupado": "",
                "grupo": "T1"
            },
            {
                "id": 6,
                "cedula": "10006",
                "nombre": "Irma",
                "apellido": "Aguilar",
                "direccion": "Calle 1 #7",
                "acudiente": "Oscar Castilo",
                "telefono": "3741504",
                "estado": "",
                "area": "",
                "trainer": "",
                "riesgo": "",
                "ruta": "",
                "fechaIni": "12-03-2024",
                "fechaFin": "13-04-2024",
                "ocupado": "",
                "grupo": "T1"
            },
            {
                "id": 7,
                "cedula": "10007",
                "nombre": "Ofeila",
                "apellido": "Lemus",
                "direccion": "Calle 1 #8",
                "acudiente": "Luis Bolanos",
                "telefono": "3785735",
                "estado": "",
                "area": "",
                "trainer": "",
                "riesgo": "",
                "ruta": "",
                "fechaIni": "12-03-2024",
                "fechaFin": "13-04-2024",
                "ocupado": "",
                "grupo": "T1"
            },
            {
                "id": 8,
                "cedula": "10008",
                "nombre": "Marcela",
                "apellido": "Loranca",
                "direccion": "Calle 1 #9",
                "acudiente": "Ricardo Palacios",
                "telefono": "3166859641",
                "estado": "",
                "area": "",
                "trainer": "",
                "riesgo": "",
                "ruta": "",
                "fechaIni": "12-03-2024",
                "fechaFin": "13-04-2024",
                "ocupado": "",
                "grupo": "T1"
            },
            {
                "id": 9,
                "cedula": "10009",
                "nombre": "Fredy",
                "apellido": "Perez",
                "direccion": "Calle 1 #10",
                "acudiente": "Gilverto Pantoja",
                "telefono": "3003158068",
                "estado": "",
                "area": "",
                "trainer": "",
                "riesgo": "",
                "ruta": "",
                "fechaIni": "12-03-2024",
                "fechaFin": "13-04-2024",
                "ocupado": "",
                "grupo": "T1"
            },
            {
                "id": 10,
                "cedula": "10010",
                "nombre": "Salomon",
                "apellido": "Alarcon",
                "direccion": "Calle 1 #11",
                "acudiente": "Gerardo Bravo",
                "telefono": "3756581",
                "estado": "",
                "area": "",
                "trainer": "",
                "riesgo": "",
                "ruta": "",
                "fechaIni": "12-03-2024",
                "fechaFin": "13-04-2024",
                "ocupado": "",
                "grupo": "T1"
            },
            {
                "id": 11,
                "cedula": "10011",
                "nombre": "Gerardo",
                "apellido": "Alarcon",
                "direccion": "Calle 1 #12",
                "acudiente": "Monica Bucheli",
                "telefono": "3012457",
                "estado": "",
                "area": "",
                "trainer": "",
                "riesgo": "",
                "ruta": "",
                "fechaIni": "12-03-2024",
                "fechaFin": "13-04-2024",
                "ocupado": "",
                "grupo": "T1"
            },
            {
                "id": 12,
                "cedula": "10012",
                "nombre": "Jose",
                "apellido": "Alcantar",
                "direccion": "Calle 1 #13",
                "acudiente": "Edwin Castro",
                "telefono": "3164959058",
                "estado": "",
                "area": "",
                "trainer": "",
                "riesgo": "",
                "ruta": "",
                "fechaIni": "12-03-2024",
                "fechaFin": "13-04-2024",
                "ocupado": "",
                "grupo": "T1"
            },
            {
                "id": 13,
                "cedula": "10013",
                "nombre": "Roberto",
                "apellido": "Martinez",
                "direccion": "Calle 1 #14",
                "acudiente": "Nelson Burbano",
                "telefono": "3047052",
                "estado": "",
                "area": "",
                "trainer": "",
                "riesgo": "",
                "ruta": "",
                "fechaIni": "12-03-2024",
                "fechaFin": "13-04-2024",
                "ocupado": "",
                "grupo": "T1"
            },
            {
                "id": 14,
                "cedula": "10014",
                "nombre": "Jacinta",
                "apellido": "Porras",
                "direccion": "Calle 1 #15",
                "acudiente": "Fernando Bustamante",
                "telefono": "3007019708",
                "estado": "",
                "area": "",
                "trainer": "",
                "riesgo": "",
                "ruta": "",
                "fechaIni": "12-03-2024",
                "fechaFin": "13-04-2024",
                "ocupado": "",
                "grupo": "T1"
            }
        ]
    },
    {
        "id": 2,
        "grupo": "M1",
        "estudiantes": [
            {
                "id": 1,
                "cedula": "20001",
                "nombre": "Juan",
                "apellido": "Alarcon",
                "direccion": "call 2 #3",
                "acudiente": "camila Alarcon",
                "telefono": "380009",
                "estado": "",
                "salon": "",
                "trainer": "",
                "riesgo": "",
                "ruta": "",
                "fechaIni": "12-03-2024",
                "fechaFin": "13-04-2024",
                "ocupado": "",
                "grupo": "M1"
            },
            {
                "id": 2,
                "cedula": "20002",
                "nombre": "Carlos",
                "apellido": "Quintana",
                "direccion": "Calle 2 #4",
                "acudiente": "Ximena Tobar",
                "telefono": "364478841",
                "estado": "",
                "salon": "",
                "trainer": "",
                "riesgo": "",
                "ruta": "",
                "fechaIni": "12-03-2024",
                "fechaFin": "13-04-2024",
                "ocupado": "",
                "grupo": "M1"
            },
            {
                "id": 3,
                "cedula": "20003",
                "nombre": "Julio",
                "apellido": "Flores",
                "direccion": "Calle 2 #5",
                "acudiente": "Aleja Torres",
                "telefono": "35789418",
                "estado": "",
                "salon": "",
                "trainer": "",
                "riesgo": "",
                "ruta": "",
                "fechaIni": "12-03-2024",
                "fechaFin": "13-04-2024",
                "ocupado": "6-10",
                "grupo": "M1"
            },
            {
                "id": 4,
                "cedula": "20004",
                "nombre": "Pedro",
                "apellido": "Diaz",
                "direccion": "Calle 2 #6",
                "acudiente": "Elena Lopez",
                "telefono": "32654879",
                "estado": "",
                "salon": "",
                "trainer": "",
                "riesgo": "",
                "ruta": "",
                "fechaIni": "12-03-2024",
                "fechaFin": "13-04-2024",
                "ocupado": "",
                "grupo": "M1"
            },
            {
                "id": 5,
                "cedula": "20005",
                "nombre": "Jesus",
                "apellido": "Aroca",
                "direccion": "Calle 2 #7",
                "acudiente": "Carlos Garcia",
                "telefono": "35984756",
                "estado": "",
                "salon": "",
                "trainer": "",
                "riesgo": "",
                "ruta": "",
                "fechaIni": "12-03-2024",
                "fechaFin": "13-04-2024",
                "ocupado": "",
                "grupo": "M1"
            },
            {
                "id": 6,
                "cedula": "20006",
                "nombre": "Wilson",
                "apellido": "Tina",
                "direccion": "Calle 2 #8",
                "acudiente": "Noe Lopez",
                "telefono": "34547812",
                "estado": "",
                "salon": "",
                "trainer": "",
                "riesgo": "",
                "ruta": "",
                "fechaIni": "12-03-2024",
                "fechaFin": "13-04-2024",
                "ocupado": "",
                "grupo": "M1"
            },
            {
                "id": 7,
                "cedula": "20007",
                "nombre": "Rosa",
                "apellido": "Flores",
                "direccion": "Calle 2 #9",
                "acudiente": "Alberto Velasquez",
                "telefono": "3006632781",
                "estado": "",
                "salon": "",
                "trainer": "",
                "riesgo": "",
                "ruta": "",
                "fechaIni": "12-03-2024",
                "fechaFin": "13-04-2024",
                "ocupado": "",
                "grupo": "M1"
            },
            {
                "id": 8,
                "cedula": "20008",
                "nombre": "Mari",
                "apellido": "Peseros",
                "direccion": "Calle 2 #10",
                "acudiente": "Evelio Jaramillo",
                "telefono": "3105244226",
                "estado": "",
                "salon": "",
                "trainer": "",
                "riesgo": "",
                "ruta": "",
                "fechaIni": "12-03-2024",
                "fechaFin": "13-04-2024",
                "ocupado": "",
                "grupo": "M1"
            },
            {
                "id": 9,
                "cedula": "20009",
                "nombre": "Maria",
                "apellido": "Rojas",
                "direccion": "Calle 2 #11",
                "acudiente": "Cecilia Alvarez",
                "telefono": "310515594",
                "estado": "",
                "salon": "",
                "trainer": "",
                "riesgo": "",
                "ruta": "",
                "fechaIni": "12-03-2024",
                "fechaFin": "13-04-2024",
                "ocupado": "",
                "grupo": "M1"
            },
            {
                "id": 10,
                "cedula": "20010",
                "nombre": "Jerardo",
                "apellido": "Bravo",
                "direccion": "Calle 2 #12",
                "acudiente": "Gerardo Ortega",
                "telefono": "3017760513",
                "estado": "",
                "salon": "",
                "trainer": "",
                "riesgo": "",
                "ruta": "",
                "fechaIni": "12-03-2024",
                "fechaFin": "13-04-2024",
                "ocupado": "",
                "grupo": "M1"
            },
            {
                "id": 11,
                "cedula": "20011",
                "nombre": "John",
                "apellido": "Peralta",
                "direccion": "Calle 2 #13",
                "acudiente": "Maria Alvarez",
                "telefono": "32548760",
                "estado": "",
                "salon": "",
                "trainer": "",
                "riesgo": "",
                "ruta": "",
                "fechaIni": "12-03-2024",
                "fechaFin": "13-04-2024",
                "ocupado": "",
                "grupo": "M1"
            },
            {
                "id": 12,
                "cedula": "20012",
                "nombre": "Geovanny",
                "apellido": "Bravo",
                "direccion": "Calle 2 #14",
                "acudiente": "Alonso Fernandez",
                "telefono": "31574894",
                "estado": "",
                "salon": "",
                "trainer": "",
                "riesgo": "",
                "ruta": "",
                "fechaIni": "12-03-2024",
                "fechaFin": "13-04-2024",
                "ocupado": "",
                "grupo": "M1"
            },
            {
                "id": 13,
                "cedula": "20013",
                "nombre": "Diana",
                "apellido": "Perez",
                "direccion": "Calle 2 #15",
                "acudiente": "Mary Alzate",
                "telefono": "32579846",
                "estado": "",
                "salon": "",
                "trainer": "",
                "riesgo": "",
                "ruta": "",
                "fechaIni": "12-03-2024",
                "fechaFin": "13-04-2024",
                "ocupado": "",
                "grupo": "M1"
            },
            {
                "id": 14,
                "cedula": "20014",
                "nombre": "Alejandra",
                "apellido": "Boa",
                "direccion": "Calle 2 #16",
                "acudiente": "Alfonso Anaya",
                "telefono": "325498267",
                "estado": "",
                "salon": "",
                "trainer": "",
                "riesgo": "",
                "ruta": "",
                "fechaIni": "12-03-2024",
                "fechaFin": "13-04-2024",
                "ocupado": "",
                "grupo": "M1"
            }
        ]
    },
    {
        "id": 3,
        "grupo": "P1",
        "estudiantes": [
            {
                "id": 1,
                "cedula": "30001",
                "nombre": "Teresa",
                "apellido": "Gomez",
                "direccion": "Calle 3 #4",
                "acudiente": "Cecilia Cardona",
                "telefono": "3182687498604",
                "estado": "",
                "salon": "",
                "trainer": "",
                "riesgo": "",
                "ruta": "",
                "fechaIni": "12-03-2024",
                "fechaFin": "13-04-2024",
                "ocupado": "",
                "grupo": "P1"
            },
            {
                "id": 2,
                "cedula": "30002",
                "nombre": "Mauricio",
                "apellido": "Zambrano",
                "direccion": "Calle 3 #5",
                "acudiente": "Andres Munoz",
                "telefono": "37768082",
                "estado": "",
                "salon": "",
                "trainer": "",
                "riesgo": "",
                "ruta": "",
                "fechaIni": "12-03-2024",
                "fechaFin": "13-04-2024",
                "ocupado": "",
                "grupo": "P1"
            },
            {
                "id": 3,
                "cedula": "30003",
                "nombre": "Martin",
                "apellido": "Pantoja",
                "direccion": "Calle 3 #6",
                "acudiente": "Yenny Castillo",
                "telefono": "3157697639",
                "estado": "",
                "salon": "",
                "trainer": "",
                "riesgo": "",
                "ruta": "",
                "fechaIni": "12-03-2024",
                "fechaFin": "13-04-2024",
                "ocupado": "",
                "grupo": "P1"
            },
            {
                "id": 4,
                "cedula": "30004",
                "nombre": "Christian",
                "apellido": "Maldonado",
                "direccion": "Calle 3 #7",
                "acudiente": "Luz Castillo",
                "telefono": "3112947401",
                "estado": "",
                "salon": "",
                "trainer": "",
                "riesgo": "",
                "ruta": "",
                "fechaIni": "12-03-2024",
                "fechaFin": "13-04-2024",
                "ocupado": "",
                "grupo": "P1"
            },
            {
                "id": 5,
                "cedula": "30005",
                "nombre": "Roger",
                "apellido": "Lozada",
                "direccion": "Calle 3 #8",
                "acudiente": "Elizabeth Guzman",
                "telefono": "3112115503",
                "estado": "",
                "salon": "",
                "trainer": "",
                "riesgo": "",
                "ruta": "",
                "fechaIni": "12-03-2024",
                "fechaFin": "13-04-2024",
                "ocupado": "",
                "grupo": "P1"
            },
            {
                "id": 6,
                "cedula": "30006",
                "nombre": "Juan",
                "apellido": "Castro",
                "direccion": "Calle 3 #9",
                "acudiente": "Gloria Castro",
                "telefono": "3123035679",
                "estado": "",
                "salon": "",
                "trainer": "",
                "riesgo": "",
                "ruta": "",
                "fechaIni": "12-03-2024",
                "fechaFin": "13-04-2024",
                "ocupado": "",
                "grupo": "P1"
            },
            {
                "id": 7,
                "cedula": "30007",
                "nombre": "Carlos",
                "apellido": "Diaz",
                "direccion": "Calle 3 #10",
                "acudiente": "Santiago Castro",
                "telefono": "3214697286",
                "estado": "",
                "salon": "",
                "trainer": "",
                "riesgo": "",
                "ruta": "",
                "fechaIni": "12-03-2024",
                "fechaFin": "13-04-2024",
                "ocupado": "",
                "grupo": "P1"
            },
            {
                "id": 8,
                "cedula": "30008",
                "nombre": "Alexander",
                "apellido": "Peñalosa",
                "direccion": "Calle 3 #11",
                "acudiente": "Alfonso Celis",
                "telefono": "3136872503",
                "estado": "",
                "salon": "",
                "trainer": "",
                "riesgo": "",
                "ruta": "",
                "fechaIni": "12-03-2024",
                "fechaFin": "13-04-2024",
                "ocupado": "",
                "grupo": "P1"
            },
            {
                "id": 9,
                "cedula": "30009",
                "nombre": "David",
                "apellido": "Cardona",
                "direccion": "Calle 3 #12",
                "acudiente": "Homero Castro",
                "telefono": "3102996772",
                "estado": "",
                "salon": "",
                "trainer": "",
                "riesgo": "",
                "ruta": "",
                "fechaIni": "12-03-2024",
                "fechaFin": "13-04-2024",
                "ocupado": "",
                "grupo": "P1"
            },
            {
                "id": 10,
                "cedula": "30010",
                "nombre": "Fernando",
                "apellido": "Valencia",
                "direccion": "Calle 3 #13",
                "acudiente": "Gladys Ceron",
                "telefono": "3216654654",
                "estado": "",
                "salon": "",
                "trainer": "",
                "riesgo": "",
                "ruta": "",
                "fechaIni": "12-03-2024",
                "fechaFin": "13-04-2024",
                "ocupado": "",
                "grupo": "P1"
            },
            {
                "id": 11,
                "cedula": "30011",
                "nombre": "Jairo",
                "apellido": "Perlaza",
                "direccion": "Calle 3 #14",
                "acudiente": "Leider Mendez",
                "telefono": "32158752",
                "estado": "",
                "salon": "",
                "trainer": "",
                "riesgo": "",
                "ruta": "",
                "fechaIni": "12-03-2024",
                "fechaFin": "13-04-2024",
                "ocupado": "",
                "grupo": "P1"
            },
            {
                "id": 12,
                "cedula": "30012",
                "nombre": "Alejandro",
                "apellido": "Reyes",
                "direccion": "Calle 3 #15",
                "acudiente": "Ricardo Acosta",
                "telefono": "32157654",
                "estado": "",
                "salon": "",
                "trainer": "",
                "riesgo": "",
                "ruta": "",
                "fechaIni": "12-03-2024",
                "fechaFin": "13-04-2024",
                "ocupado": "",
                "grupo": "P1"
            },
            {
                "id": 13,
                "cedula": "30013",
                "nombre": "Claudia",
                "apellido": "Cardozo",
                "direccion": "Calle 3 #16",
                "acudiente": "Jose Fausto",
                "telefono": "",
                "estado": "",
                "salon": "",
                "trainer": "",
                "riesgo": "",
                "ruta": "",
                "fechaIni": "12-03-2024",
                "fechaFin": "13-04-2024",
                "ocupado": "",
                "grupo": "P1"
            },
            {
                "id": 14,
                "cedula": "30014",
                "nombre": "Fabio",
                "apellido": "Zambrano",
                "direccion": "Calle 3 #17",
                "acudiente": "William Herrera",
                "telefono": "312479574",
                "estado": "",
                "salon": "",
                "trainer": "",
                "riesgo": "",
                "ruta": "",
                "fechaIni": "12-03-2024",
                "fechaFin": "13-04-2024",
                "ocupado": "",
                "grupo": "P1"
            }
        ]
    },
    {
        "id": 4,
        "grupo": "T2",
        "estudiantes": [
            {
                "id": 1,
                "cedula": "40001",
                "nombre": "Yaned",
                "apellido": "Rojas",
                "direccion": "Calle 4 #5",
                "acudiente": "Maria Contreras",
                "telefono": "3137844603",
                "estado": "",
                "salon": "",
                "trainer": "",
                "riesgo": "",
                "ruta": "",
                "fechaIni": "12-03-2024",
                "fechaFin": "13-04-2024",
                "ocupado": "",
                "grupo": "T2"
            },
            {
                "id": 2,
                "cedula": "40002",
                "nombre": "Luz",
                "apellido": "Piso",
                "direccion": "Calle 4 #6",
                "acudiente": "Alexander Jaramillo",
                "telefono": "345789621",
                "estado": "",
                "salon": "",
                "trainer": "",
                "riesgo": "",
                "ruta": "",
                "fechaIni": "12-03-2024",
                "fechaFin": "13-04-2024",
                "ocupado": "",
                "grupo": "T2"
            },
            {
                "id": 3,
                "cedula": "40003",
                "nombre": "Maria",
                "apellido": "Bolaños",
                "direccion": "Calle 4 #7",
                "acudiente": "Juan Gutierrez",
                "telefono": "356487921",
                "estado": "",
                "salon": "",
                "trainer": "",
                "riesgo": "",
                "ruta": "",
                "fechaIni": "12-03-2024",
                "fechaFin": "13-04-2024",
                "ocupado": "",
                "grupo": "T2"
            },
            {
                "id": 4,
                "cedula": "40004",
                "nombre": "Yury",
                "apellido": "Tobar",
                "direccion": "Calle 4 #8",
                "acudiente": "Esmith Moncada",
                "telefono": "369587425",
                "estado": "",
                "salon": "",
                "trainer": "",
                "riesgo": "",
                "ruta": "",
                "fechaIni": "12-03-2024",
                "fechaFin": "13-04-2024",
                "ocupado": "",
                "grupo": "T2"
            },
            {
                "id": 5,
                "cedula":"400005",
                "nombre": "Alexandra",
                "apellido": "Tobos",
                "direccion": "Calle 4 #9",
                "acudiente": "Janneth Becerra",
                "telefono": "355948488",
                "estado": "",
                "salon": "",
                "trainer": "",
                "riesgo": "",
                "ruta": "",
                "fechaIni": "12-03-2024",
                "fechaFin": "13-04-2024",
                "ocupado": "",
                "grupo": "T2"
            },
            {
                "id": 6,
                "cedula": "40006",
                "nombre": "Beatriz",
                "apellido": "Chavez",
                "direccion": "Calle 4 #10",
                "acudiente": "Liliana Martinez",
                "telefono": "351547475",
                "estado": "",
                "salon": "",
                "trainer": "",
                "riesgo": "",
                "ruta": "",
                "fechaIni": "12-03-2024",
                "fechaFin": "13-04-2024",
                "ocupado": "",
                "grupo": "T2"
            },
            {
                "id": 7,
                "cedula": "40007",
                "nombre": "Elena",
                "apellido": "Cardona",
                "direccion": "Calle 4 #11",
                "acudiente": "Hector Molina",
                "telefono": "354877578",
                "estado": "",
                "salon": "",
                "trainer": "",
                "riesgo": "",
                "ruta": "",
                "fechaIni": "12-03-2024",
                "fechaFin": "13-04-2024",
                "ocupado": "",
                "grupo": "T2"
            },
            {
                "id": 8,
                "cedula": "40008",
                "nombre": "Ninfa",
                "apellido": "Vargas",
                "direccion": "Calle 4 #12",
                "acudiente": "Julia Berdugo",
                "telefono": "356899472",
                "estado": "",
                "salon": "",
                "trainer": "",
                "riesgo": "",
                "ruta": "",
                "fechaIni": "12-03-2024",
                "fechaFin": "13-04-2024",
                "ocupado": "",
                "grupo": "T2"
            },
            {
                "id": 9,
                "cedula": "40009",
                "nombre": "Gloria",
                "apellido": "Hernandez",
                "direccion": "Calle 4 #13",
                "acudiente": "Francely Vera",
                "telefono": "3236519549",
                "estado": "",
                "salon": "",
                "trainer": "",
                "riesgo": "",
                "ruta": "",
                "fechaIni": "12-03-2024",
                "fechaFin": "13-04-2024",
                "ocupado": "",
                "grupo": "T2"
            },
            {
                "id": 10,
                "cedula": "40010",
                "nombre": "Laura",
                "apellido": "Amaya",
                "direccion": "Calle 4 #14",
                "acudiente": "Edwin Lopera",
                "telefono": "319874897",
                "estado": "",
                "salon": "",
                "trainer": "",
                "riesgo": "",
                "ruta": "",
                "fechaIni": "12-03-2024",
                "fechaFin": "13-04-2024",
                "ocupado": "",
                "grupo": "T2"
            },
            {
                "id": 11,
                "cedula": "40011",
                "nombre": "Diana",
                "apellido": "Arango",
                "direccion": "Calle 4 #15",
                "acudiente": "Carolina Parra",
                "telefono": "3614987494",
                "estado": "",
                "salon": "",
                "trainer": "",
                "riesgo": "",
                "ruta": "",
                "fechaIni": "12-03-2024",
                "fechaFin": "13-04-2024",
                "ocupado": "",
                "grupo": "T2"
            },
            {
                "id": 12,
                "cedula": "40012",
                "nombre": "Angela",
                "apellido": "Gomez",
                "direccion": "Calle 4 #16",
                "acudiente": "Rosa Rivera",
                "telefono": "3651949874",
                "estado": "",
                "salon": "",
                "trainer": "",
                "riesgo": "",
                "ruta": "",
                "fechaIni": "12-03-2024",
                "fechaFin": "13-04-2024",
                "ocupado": "",
                "grupo": "T2"
            },
            {
                "id": 13,
                "cedula": "40013",
                "nombre": "Amparo",
                "apellido": "Cortes",
                "direccion": "Calle 4 #17",
                "acudiente": "Teresa Hurtado",
                "telefono": "3451984985",
                "estado": "",
                "salon": "",
                "trainer": "",
                "riesgo": "",
                "ruta": "",
                "fechaIni": "12-03-2024",
                "fechaFin": "13-04-2024",
                "ocupado": "",
                "grupo": "T2"
            },
            {
                "id": 14,
                "cedula": "40014",
                "nombre": "Martha",
                "apellido": "Uribe",
                "direccion": "Calle 4 #18",
                "acudiente": "Edgar Riascos",
                "telefono": "361948974",
                "estado": "",
                "salon": "",
                "trainer": "",
                "riesgo": "",
                "ruta": "",
                "fechaIni": "12-03-2024",
                "fechaFin": "13-04-2024",
                "ocupado": "",
                "grupo": "T2"
            }
        ]
    }
];


alert("Bienvenido Coordinador");
console.log("Haz iniciado como el Coordinador de Campuslands");

let campers = [];

const loadCampers = () => {
    const data = localStorage.getItem('campers');
    if (data) {
        campers = JSON.parse(data);
        renderCampers();
    }
};

const saveCampers = () => {
    localStorage.setItem('campers', JSON.stringify(campers));
};

const renderCampers = () => {
    const camperList = document.getElementById('camperList');
    camperList.innerHTML = ''; 
    campers.forEach(camper => {
        const li = document.createElement('li');
        li.textContent = `${camper.identificacion} - ${camper.nombres} ${camper.apellidos} ${camper.ruta_entrenamiento} (${camper.estado})`;
        camperList.appendChild(li);
    });
};

const addCamper = () => {
    const identificacion = document.getElementById('identificacion').value;
    const nombres = document.getElementById('nombres').value;
    const apellidos = document.getElementById('apellidos').value;
    const direccion = document.getElementById('direccion').value;
    const acudiente = document.getElementById('acudiente').value;
    const celular = document.getElementById('celular').value;
    const practica = document.getElementById('practica').value;
    const teorica = document.getElementById('teorica').value;
    const estado = document.getElementById('estado').value;
    const riesgo = document.getElementById('riesgo').value;
    const ruta = document.getElementById('ruta').value;

riesgo = (practica+teorica)/2;

    const camper = {
        identificacion,
        nombres,
        apellidos,
        direccion,
        acudiente,
        telefonos: { celular },
        practica,
        teorica,
        estado,
        riesgo,
        ruta_entrenamiento: ruta,
    };

    campers.push(camper);
    saveCampers();
    renderCampers();
    
    document.getElementById('camperForm').reset();
};
const formatList = () => {
    campers = [];
    saveCampers();
    renderCampers();
};
window.onload = loadCampers;

const addNotas = estudiantes.push(id);
document.getElementById